version: '3.4'

services:
  mars.web:
    image: ${DOCKER_REGISTRY-}marsweb
    build:
      context: .
      dockerfile: Mars.Web/Dockerfile
    environment:
      - SeqServer=http://seq
    networks:
      - jaegernet

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "8888:80"
    volumes:
      - /datadrive:/data
    environment:
      - ACCEPT_EULA=Y

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ~/source/repos/mars_rover2/src/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    volumes:
     - ~/source/repos/mars_rover2/src/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    ports:
     - 3000:3000
    links:
      - prometheus

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - jaegernet
    depends_on:
      - mars.web

networks:
  jaegernet: